apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-https-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-https-app
  template:
    metadata:
      labels:
        app: simple-https-app
    spec:
      containers:
      - name: simple-https-app
        image: soumyakube/simple-https-app:latest
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: tls-certs
          mountPath: /etc/ssl/certs
          readOnly: true
      volumes: 
      - name: tls-certs
        secret:
          secretName: my-tls-secret
---
apiVersion: v1
kind: Service
metadata:
  name: simple-https-app-service
spec:
  selector:
    app: simple-https-app
  ports:
    - protocol: TCP
      port: 443
      targetPort: 3000
  type: LoadBalancer
