apiVersion: v1
kind: PersistentVolume
metadata:
  name: simple-https-app-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce 
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /data/simple-https-app
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: simple-https-app-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
